### ISSUE TITLE
Error running webpack-ts

### ISSUE THREAD

**Issue by Keating950** [GaryB432/gb-generators#26]
I get the following error running the webpack-ts generator, but only when declining to include a Workbox service worker and selecting 'None' for the testing library:
<details><summary>Output</summary>
[REDACTED] is where I have node installed, naturally.

    node:events:356
          throw er; // Unhandled 'error' event
          ^
    
    TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'Environment'
        |     property '_rootGenerator' -> object with constructor 'default_1'
        |     property 'options' -> object with constructor 'Object'
        --- property 'env' closes the circle
        at JSON.stringify (<anonymous>)
        at default_1.writing ([REDACTED]/lib/node_modules/generator-webpack-ts/generators/tester/index.js:72:38)
        at Object.<anonymous> ([REDACTED]/lib/node_modules/generator-webpack-ts/node_modules/yeoman-generator/lib/index.js:991:25)
        at [REDACTED]/lib/node_modules/generator-webpack-ts/node_modules/run-async/index.js:49:25
        at new Promise (<anonymous)
        at [REDACTED]/lib/node_modules/generator-webpack-ts/node_modules/run-async/index.js:26:19
        at runLoop.add.once.once ([REDACTED]/lib/node_modules/generator-webpack-ts/node_modules/yeoman-generator/lib/index.js:992:11)
        at processImmediate (node:internal/timers:463:21)
    Emitted 'error' event on default_1 instance at:
        at Immediate.<anonymous> ([REDACTED]/lib/node_modules/generator-webpack-ts/node_modules/yeoman-generator/lib/index.js:1022:2>
</details>

**Comment by GaryB432** [comment]
thanks for reporting this! `6.15.2` should work for you
